version: '3'

services:
  database-mariadb:
    container_name: database-mariadb
    restart: always
    image: mariadb

    environment:
      MARIADB_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul

    volumes:
      - ./mariadb-init.d:/docker-entrypoint-initdb.d

    ports:
      - '3306:3306'

#    command:
#      - '--character-set-server=utf8mb4'
#      - '--collation-server=utf8mb4_unicode_ci'

#  chat-server:
#    image: chat-server:spring-boot
#    container_name: service-chat
#    build:
#      context: ../chat-server
#      dockerfile: ../chat-server/Dockerfile
#    restart: always
#    ports:
#      - '8080:8080'
#    networks:
#      - default

  angular-app:
    image: nginx-server:web-server
    container_name: angular-app
    build:
      context: ../nginx-server
      dockerfile: ../nginx-server/Dockerfile
    ports:
      - "80:80"
  springboot3oauth2authorizationserver:
    image: springboot3-oauth2-authorizationserver:0.0.1-SNAPSHOT
    build:
      context: ../oauth2server
      dockerfile: ../oauth2server/Dockerfile
    ports:
      - "9090:9090"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
#  nginx:
#    image: nginx:latest
###    volumes:
###      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - angular-app
networks:
  default:
